### ISSUE TITLE
memory performance

### ISSUE THREAD

**Issue by synikitin** [tnagler/kdevine#3]
Hi again. I profiled

```
if (!require(profvis)) install.packages("profvis")
library(kdevine)

data(wdbc)
wdbc[wdbc == 0] <- .Machine$double.eps

profvis::profvis(
  kdevine(as.matrix(wdbc[sample(nrow(wdbc), 2e4, replace = TRUE), 2:6]),
                           xmin = rep(0, 5), cores = 1, info = FALSE)
)
```

 with profvis and have noticed that ~82% of time is spent on garbage collection. For a dataset of  ~2 Mb, ~100 Gb worth of objects was allocated and destroyed. 

Do you have any insight into why that is happening and whether any fixes come to mind?

**Comment by tnagler** [comment]
Unfortunately, profvis cannot look into C++ code, so I don't know exactly what's going on. I don't think all the time is actually spent on garbage collection, but profvis has no way to see what's going on inside the C++ function. 

I Also don't think it's a big problem that a lot of memory is allocated and deallocated. In my system monitor I don't see a big spike in memory usage, so there is actually very little memory used at each point in time.

But there is a way to make it run faster. If `xmin` is set, the integrated kernel has to be evaluated 4 times in `pkde1d` which is a lot of work. The issue is alleviated quite a bit if  you leave `xmin` unspecified. If you have positive data, it may be more reasonable to log-transform the data before applying `kdevine`. Then you don't have to use `xmin` and the code should run much faster.
